name: GITACTION
 #test
 on:
 
push:

   branches: [ "main"]

pull_request:

   branches: [ "main"]
 
 
workflow_dispatch:

inputs:
environment:
description: "Environment to run test again"
type : string
required : true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

     - uses: actions/setup-node@v3.9.1

     - name: Setup Node.js environment

       run: Test action
